### ISSUE TITLE
Add CR status checker

### ISSUE THREAD

**Issue by KryukovaPolina** [Netcracker/qubership-test-pipelines#26]
### Is your feature request related to a problem? Please describe

For services where there is no Status Provisioner, we can check the installation status using CR
CR yaml contains conditions:
```
  conditions:
    - lastTransitionTime: 2025-06-18 06:24:59.072427696 +0000 UTC m=+971.803009363
      message: The deployment readiness status check failed
      reason: ReconcileCycleStatus
      status: 'False'
      type: Failed
```

Status should be 'True'

### Describe the solution you'd like

Add script to pipeline for checking status in CR
